package uz.bukhara.countrybot.bot.util;

public interface BotState {
    String MAIN_MENU="MAIN_MENU";
    String MENU="MENU";
    String INFO="INFO";
    String SEARCH_COUNTRY_EDIT="SEARCH_COUNTRY_EDIT";
    String SEARCH_COUNTRY_SEND="SEARCH_COUNTRY_SEND";
    String SEARCH_WITH_LOCATION="SEARCH_WITH_LOCATION";
    String SEARCH="SEARCH";
    String WRITING="WRITING";
    String LIST_OF_COUNTRIES_SEND="LIST_OF_COUNTRIES_SEND";
    String LIST_OF_COUNTRIES_EDIT="LIST_OF_COUNTRIES_EDIT";
    String DATA_OF_COUNTRY_EDIT="DATA_OF_COUNTRY_EDIT";
    String DATA_OF_COUNTRY_SEND="DATA_OF_COUNTRY_SEND";
    String CURRENCY_OF_COUNTRY="CURRENCY_OF_COUNTRY";
    String LANGUAGE_OF_COUNTRY="LANGUAGE_OF_COUNTRY";
    String BORDERS_OF_COUNTRY="BORDERS_OF_COUNTRY";
    String TIME_ZONES_OF_COUNTRY="TIME_ZONES_OF_COUNTRY";
    String FLAG_OF_COUNTRY="FLAG_OF_COUNTRY";

}
